import { test_abs } from './functions/abs.test';
import { test_adj } from './functions/adj.test';
import { test_approxratio } from './functions/approxratio.test';
import { test_arccos } from './functions/arccos.test';
import { test_arccosh } from './functions/arccosh.test';
import { test_arcsin } from './functions/arcsin.test';
import { test_arcsinh } from './functions/arcsinh.test';
import { test_arctan } from './functions/arctan.test';
import { test_arctanh } from './functions/arctanh.test';
import { test_arg } from './functions/arg.test';
import { test_assignments } from './functions/assignments.test';
import { test_bake } from './functions/bake.test';
import { test_besselj } from './functions/besselj.test';
import { test_bessely } from './functions/bessely.test';
import { test_signs_in_rationals } from './functions/bignum.test';
import { test_binomial } from './functions/binomial.test';
import { test_ceiling } from './functions/ceiling.test';
import { test_check } from './functions/check.test';
import { test_choose } from './functions/choose.test';
import { test_circexp } from './functions/circexp.test';
import { test_clearall } from './functions/clearall.test';
import { test_clock } from './functions/clock.test';
import { test_coeff } from './functions/coeff.test';
import { test_cofactor } from './functions/cofactor.test';
import { test_condense } from './functions/condense.test';
import { test_contract } from './functions/contract.test';
import { test_cos } from './functions/cos.test';
import { test_cosh } from './functions/cosh.test';
import { test_defint } from './functions/defint.test';
import { test_denominator } from './functions/denominator.test';
import { test_dependencies } from './functions/dependencies.test';
import { test_derivative } from './functions/derivative.test';
import { test_dirac } from './functions/dirac.test';
import { test_divisors } from './functions/divisors.test';
import { test_eigen } from './functions/eigen.test';
import { test_erf } from './functions/erf.test';
import { test_erfc } from './functions/erfc.test';
import { test_exp } from './functions/exp.test';
import { test_expand } from './functions/expand.test';
import { test_expcos } from './functions/expcos.test';
import { test_expsin } from './functions/expsin.test';
import { test_factor_number } from './functions/factor.test';
import { test_factorpoly } from './functions/factorpoly.test';
import { test_float } from './functions/float.test';
import { test_floor } from './functions/floor.test';
import { test_for } from './functions/for.test';
import { test_gamma } from './functions/gamma.test';
import { test_gcd } from './functions/gcd.test';
import { test_hermite } from './functions/hermite.test';
import { test_imag } from './functions/imag.test';
import { test_index } from './functions/index.test';
import { test_integral } from './functions/integral.test';
import { test_isprime } from './functions/isprime.test';
import { test_laguerre } from './functions/laguerre.test';
import { test_lcm } from './functions/lcm.test';
import { test_legendre } from './functions/legendre.test';
import { test_log } from './functions/log.test';
import { mini_test } from './functions/mini-test.test';
import { test_mod } from './functions/mod.test';
import { test_multiply } from './functions/multiply.test';
import { test_nroots } from './functions/nroots.test';
import { test_numerator } from './functions/numerator.test';
import { test_outer } from './functions/outer.test';
import { test_pattern } from './functions/pattern.test';
import { test_polar } from './functions/polar.test';
import { test_power } from './functions/power.test';
import { test_printlatex } from './functions/printlatex.test';
import { test_product } from './functions/product.test';
import { test_quickfactor } from './functions/quickfactor.test';
import { test_quotient } from './functions/quotient.test';
import { test_rationalize } from './functions/rationalize.test';
import { test_real } from './functions/real.test';
import { test_rect } from './functions/rect.test';
import { test_roots } from './functions/roots.test';
import { test_round } from './functions/round.test';
import { test_scan } from './functions/scan.test';
import { test_sgn } from './functions/sgn.test';
import { test_shape } from './functions/shape.test';
import { test_simplify } from './functions/simplify.test';
import { test_sin } from './functions/sin.test';
import { test_sinh } from './functions/sinh.test';
import { test_subst } from './functions/subst.test';
import { test_sum } from './functions/sum.test';
import { test_tan } from './functions/tan.test';
import { test_tanh } from './functions/tanh.test';
import { test_taylor } from './functions/taylor.test';
import { test_tensor } from './functions/tensor.test';
import { test_zero } from './functions/zero.test';
import { test_transpose } from './functions/transpose.test';

import { test_low_level } from './low_level.test';

export function testall() {
  test_low_level();
  test_pattern();
  test_abs();
  test_sum();
  test_product();
  test_for();
  test_exp();
  test_expand();
  test_factorpoly();
  test_subst();
  test_simplify();
  test_multiply();
  test_scan();
  test_power();
  test_factor_number(); // long
  test_tensor();
  test_bake();
  test_adj();
  test_arg();
  test_approxratio();
  test_besselj();
  test_bessely();
  test_ceiling();
  test_choose();
  test_circexp();
  test_clock();
  test_cofactor();
  test_condense();
  test_contract();
  test_defint(); // very long
  test_denominator();
  test_derivative();
  test_dirac();
  test_erf();
  test_erfc();
  test_expcos();
  test_expsin();
  test_float();
  test_floor();
  test_gamma();
  test_gcd();
  test_imag();
  test_lcm();
  test_log();
  test_mod();
  test_nroots();
  test_numerator();
  test_outer();
  test_polar();
  test_quotient();
  test_rationalize();
  test_real();
  test_rect();
  test_round();
  test_sgn();
  test_taylor();
  test_zero();
  test_hermite();
  test_laguerre();
  test_legendre();
  test_binomial();
  test_divisors();
  test_coeff();
  test_sin();
  test_cos();
  test_tan();
  test_sinh();
  test_cosh();
  test_tanh();
  test_arcsin();
  test_arcsinh();
  test_arccos();
  test_arccosh();
  test_arctan();
  test_arctanh();
  test_index();
  test_isprime();
  test_eigen();
  test_shape();
  mini_test();
  test_quickfactor();
  test_integral();
  test_roots();
  test_transpose();
  test_printlatex();
}

testall();
