const { test_abs } = require('./functions/abs.test');
const { test_adj } = require('./functions/adj.test');
const { test_approxratio } = require('./functions/approxratio.test');
const { test_arccos } = require('./functions/arccos.test');
const { test_arccosh } = require('./functions/arccosh.test');
const { test_arcsin } = require('./functions/arcsin.test');
const { test_arcsinh } = require('./functions/arcsinh.test');
const { test_arctan } = require('./functions/arctan.test');
const { test_arctanh } = require('./functions/arctanh.test');
const { test_arg } = require('./functions/arg.test');
const { test_assignments } = require('./functions/assignments.test');
const { test_bake } = require('./functions/bake.test');
const { test_besselj } = require('./functions/besselj.test');
const { test_bessely } = require('./functions/bessely.test');
const { test_signs_in_rationals } = require('./functions/bignum.test');
const { test_binomial } = require('./functions/binomial.test');
const { test_ceiling } = require('./functions/ceiling.test');
const { test_check } = require('./functions/check.test');
const { test_choose } = require('./functions/choose.test');
const { test_circexp } = require('./functions/circexp.test');
const { test_clearall } = require('./functions/clearall.test');
const { test_clock } = require('./functions/clock.test');
const { test_coeff } = require('./functions/coeff.test');
const { test_cofactor } = require('./functions/cofactor.test');
const { test_condense } = require('./functions/condense.test');
const { test_contract } = require('./functions/contract.test');
const { test_cos } = require('./functions/cos.test');
const { test_cosh } = require('./functions/cosh.test');
const { test_defint } = require('./functions/defint.test');
const { test_denominator } = require('./functions/denominator.test');
const { test_dependencies } = require('./functions/dependencies.test');
const { test_derivative } = require('./functions/derivative.test');
const { test_dirac } = require('./functions/dirac.test');
const { test_divisors } = require('./functions/divisors.test');
const { test_eigen } = require('./functions/eigen.test');
const { test_erf } = require('./functions/erf.test');
const { test_erfc } = require('./functions/erfc.test');
const { test_exp } = require('./functions/exp.test');
const { test_expand } = require('./functions/expand.test');
const { test_expcos } = require('./functions/expcos.test');
const { test_expsin } = require('./functions/expsin.test');
const { test_factor_number } = require('./functions/factor.test');
const { test_factorpoly } = require('./functions/factorpoly.test');
const { test_float } = require('./functions/float.test');
const { test_floor } = require('./functions/floor.test');
const { test_for } = require('./functions/for.test');
const { test_gamma } = require('./functions/gamma.test');
const { test_gcd } = require('./functions/gcd.test');
const { test_hermite } = require('./functions/hermite.test');
const { test_imag } = require('./functions/imag.test');
const { test_index } = require('./functions/index.test');
const { test_integral } = require('./functions/integral.test');
const { test_isprime } = require('./functions/isprime.test');
const { test_laguerre } = require('./functions/laguerre.test');
const { test_lcm } = require('./functions/lcm.test');
const { test_legendre } = require('./functions/legendre.test');
const { test_log } = require('./functions/log.test');
const { test_mini_test } = require('./functions/mini-test.test');
const { test_mod } = require('./functions/mod.test');
const { test_multiply } = require('./functions/multiply.test');
const { test_nroots } = require('./functions/nroots.test');
const { test_numerator } = require('./functions/numerator.test');
const { test_outer } = require('./functions/outer.test');
const { test_pattern } = require('./functions/pattern.test');
const { test_polar } = require('./functions/polar.test');
const { test_power } = require('./functions/power.test');
const { test_printlatex } = require('./functions/printlatex.test');
const { test_product } = require('./functions/product.test');
const { test_quickfactor } = require('./functions/quickfactor.test');
const { test_quotient } = require('./functions/quotient.test');
const { test_rationalize } = require('./functions/rationalize.test');
const { test_real } = require('./functions/real.test');
const { test_rect } = require('./functions/rect.test');
const { test_roots } = require('./functions/roots.test');
const { test_round } = require('./functions/round.test');
const { test_scan } = require('./functions/scan.test');
const { test_sgn } = require('./functions/sgn.test');
const { test_shape } = require('./functions/shape.test');
const { test_simplify } = require('./functions/simplify.test');
const { test_sin } = require('./functions/sin.test');
const { test_sinh } = require('./functions/sinh.test');
const { test_subst } = require('./functions/subst.test');
const { test_sum } = require('./functions/sum.test');
const { test_tan } = require('./functions/tan.test');
const { test_tanh } = require('./functions/tanh.test');
const { test_taylor } = require('./functions/taylor.test');
const { test_tensor } = require('./functions/tensor.test');
const { test_zero } = require('./functions/zero.test');

const { test_low_level } = require('./low_level.test');

// eslint-disable-next-line require-jsdoc
export function selftest() {
  // test_low_level();
  // test_pattern();
  test_abs();
  test_sum();
  test_product();
  test_for();
  test_exp();
  test_expand();
  test_factorpoly();
  test_subst();
  test_simplify();
  test_multiply();
  test_scan();
  test_power();
  test_factor_number(); // long
  test_tensor();
  test_bake();
  test_adj();
  test_arg();
  test_approxratio();
  test_besselj();
  test_bessely();
  test_ceiling();
  test_choose();
  test_circexp();
  test_clock();
  test_cofactor();
  test_condense();
  test_contract();
  test_defint(); // very long
  test_denominator();
  test_derivative();
  test_dirac();
  test_erf();
  test_erfc();
  test_expcos();
  test_expsin();
  test_float();
  test_floor();
  test_gamma();
  test_gcd();
  test_imag();
  test_lcm();
  test_log();
  test_mod();
  test_nroots();
  test_numerator();
  test_outer();
  test_polar();
  test_quotient();
  test_rationalize();
  test_real();
  test_rect();
  test_round();
  test_sgn();
  test_taylor();
  test_zero();
  test_hermite();
  test_laguerre();
  test_legendre();
  test_binomial();
  test_divisors();
  test_coeff();
  test_sin();
  test_cos();
  test_tan();
  test_sinh();
  test_cosh();
  test_tanh();
  test_arcsin();
  test_arcsinh();
  test_arccos();
  test_arccosh();
  test_arctan();
  test_arctanh();
  test_index();
  test_isprime();
  test_eigen();
  test_shape();
  mini_test();
  test_quickfactor();
  test_integral();
  test_roots();
}

selftest();
